spring.application.name=Todo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=pass
spring.h2.console.enabled=true
#spring.security.user.name=sxew
#spring.security.user.password=pass
