spring.application.name=Todo
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=pass
#spring.h2.console.enabled=true
#spring.security.user.name=sxew
#spring.security.user.password=pass
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_USERPASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.security.user.name=${APP_USERNAME}
#spring.security.user.password=${APP_PASSWORD}